db.getCollection('restaurante').find();
db.getCollection('restaurante').find({}, {restaurant_id : 1, name : 1, borough : 1, cuisine :1});
db.getCollection('restaurante').find({}, {restaurant_id : 1, name : 1, borough : 1, cuisine :1, _id : 0});
db.getCollection('restaurante').find({},{ restaurant_id: 1, name: 1, borough: 1, 'address.zipcode': 1, _id: 0});
db.getCollection('restaurante').find({ borough: 'Bronx' });
db.getCollection('restaurante').find({ borough: 'Bronx' }).limit(5);
db.getCollection('restaurante').find({ borough: 'Bronx' }).limit(5).skip(5);
db.getCollection('restaurante').aggregate([ {$group:{_id:"$name", score_total:{$sum:{$sum : "$grades.score"}}}}, {$match:{score_total:{$gt:90}}} ]);
db.getCollection('restaurante').aggregate([ {$group:{_id:"$name", score_total:{$sum:{$sum : "$grades.score"}}}}, {$match:{score_total:{$gt:80, $lt:100}}} ]);
db.getCollection('restaurante').find({"address.coord":{$lt:-95.754168}});
db.getCollection('restaurante').aggregate([ {$group:{_id:"$name", score_total:{$sum:{$sum : "$grades.score"}}}}, {$match:{score_total:{$gt:70}, cuisine:{$ne : 'American'},"address.coord":{$lt:-65.754168}}} ]);
db.getCollection('restaurante').aggregate([ {$group:{_id:"$name", score_total:{$sum:{$sum : "$grades.score"}}}}, {$match:{score_total:{$gt:70}, cuisine:{$ne : 'American'},"address.coord":{$lt:-65.754168}}} ]);
db.getCollection('restaurante').find({$and:[{cuisine:{$ne : 'American'},"grades.grade": "A", borough:{$ne : 'Brooklyn'}}]}).sort({cuisine:-1});
db.getCollection('restaurante').find({name : /^Wil/},{restaurant_id: 1, name: 1, borough: 1, cuisine: 1});
db.getCollection('restaurante').find({name : /ces$/},{restaurant_id: 1, name: 1, borough: 1, cuisine: 1});
db.getCollection('restaurante').find({name : /Reg/},{restaurant_id: 1, name: 1, borough: 1, cuisine: 1});
db.getCollection('restaurante').find({$and: [{$or:[{cuisine:'American'},{cuisine:'Chinese'}]},{borough:'Bronx'}]});
db.getCollection('restaurante').find({borough: {$in:['State Island','Queens','Bronx','Brooklyn']}},{ restaurant_id: 1, name: 1, borough: 1, cuisine:1});
db.getCollection('restaurante').find({borough: {$nin:['State Island','Queens','Bronx','Brooklyn']}},{ restaurant_id: 1, name: 1, borough: 1, cuisine:1});
db.getCollection('restaurante').find({"grades.score":{$not:{$gt:10}}},{ restaurant_id: 1, name: 1, borough: 1, cuisine:1});
db.getCollection('restaurante').find({$or:[{$and:[{cuisine:"Seafood"},{cuisine: {$nin:['American','Chinese']}}]},{name: /^Wil/}]},{ restaurant_id: 1, name: 1, borough: 1, cuisine:1});
db.getCollection('restaurante').find({grades:{$elemMatch:{date:ISODate("2014-08-11T00:00:00Z"),score:11,grade:'A'}}},{ restaurant_id: 1, name: 1, grades:1});
db.getCollection('restaurante').aggregate({$project:{ restaurant_id: 1, name: 1, grades:{$arrayElemAt:["$grades",2]}}},{$match:{grades:{$elemMatch:{date:ISODate("2014-08-11T00:00:00Z"),score:{$gt:9},grade:'A'}}}});
db.getCollection('restaurante').find({'address.coord.1':{$gt:42,$lte:52}},{restaurant_id:1, name:1, address:1});
db.getCollection('restaurante').find({}).sort({name:1});
db.getCollection('restaurante').find({}).sort({name:-1});
db.getCollection('restaurante').find({}).sort({cuisine:1, borough:-1});
db.getCollection('restaurante').find({"address.street":null});
db.getCollection('restaurante').find({"address.coord":{$type:1}});
db.getCollection('restaurante').find({"grades.score":{$mod:[7,0]}},{restaurant_id: 1, name: 1, grades : 1});
db.getCollection('restaurante').find({name: /mon/},{name: 1, borough : 1, "address.coord" : 1, cuisine : 1});
db.getCollection('restaurante').find({name: /^Mad/},{name: 1, borough : 1, "address.coord" : 1, cuisine : 1});