-- MySQL Script generated by MySQL Workbench
-- Wed Feb  7 10:35:13 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `Pizzeria` ;

-- -----------------------------------------------------
-- Table `Pizzeria`.`provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`provincia` (
  `idProvincia` SMALLINT UNSIGNED NOT NULL,
  `nombreProvincia` VARCHAR(30) NULL,
  PRIMARY KEY (`idProvincia`),
  UNIQUE INDEX `idProvincia_UNIQUE` (`idProvincia` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`localidad` (
  `idLocalidad` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombreLocalidad` VARCHAR(45) NULL,
  `provinciaId` SMALLINT UNSIGNED NULL,
  PRIMARY KEY (`idLocalidad`),
  UNIQUE INDEX `iLlocalidad_UNIQUE` (`idLocalidad` ASC) VISIBLE,
  INDEX `Provincia_idx` (`provinciaId` ASC) VISIBLE,
  CONSTRAINT `Provincia`
    FOREIGN KEY (`provinciaId`)
    REFERENCES `Pizzeria`.`provincia` (`idProvincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`codigoPostal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`codigoPostal` (
  `idCodigoPostal` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(5) NULL,
  `localidadId` SMALLINT UNSIGNED NULL,
  PRIMARY KEY (`idCodigoPostal`),
  UNIQUE INDEX `idCodigoPostal_UNIQUE` (`idCodigoPostal` ASC) VISIBLE,
  INDEX `localidad_idx` (`localidadId` ASC) VISIBLE,
  CONSTRAINT `localidad`
    FOREIGN KEY (`localidadId`)
    REFERENCES `Pizzeria`.`localidad` (`idLocalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`cliente` (
  `idCliente` SMALLINT UNSIGNED NOT NULL,
  `nombre` VARCHAR(15) NULL,
  `apellidos` VARCHAR(45) NULL,
  `direccion` VARCHAR(65) NULL,
  `codigoPostalId` SMALLINT UNSIGNED NULL,
  `telefono` VARCHAR(15) NULL,
  `LocalidadId` SMALLINT UNSIGNED NULL,
  `ProvinciaId` SMALLINT UNSIGNED NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `idCliente_UNIQUE` (`idCliente` ASC) VISIBLE,
  INDEX `Provincia_idx` (`ProvinciaId` ASC) VISIBLE,
  INDEX `localidad_cliente_idx` (`LocalidadId` ASC) VISIBLE,
  INDEX `codigoPostal_cliente_idx` (`codigoPostalId` ASC) VISIBLE,
  CONSTRAINT `provincia_cliente`
    FOREIGN KEY (`ProvinciaId`)
    REFERENCES `Pizzeria`.`provincia` (`idProvincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `localidad_cliente`
    FOREIGN KEY (`LocalidadId`)
    REFERENCES `Pizzeria`.`localidad` (`idLocalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `codigoPostal_cliente`
    FOREIGN KEY (`codigoPostalId`)
    REFERENCES `Pizzeria`.`codigoPostal` (`idCodigoPostal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`tipoEnvio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`tipoEnvio` (
  `idTipoEnvio` TINYINT UNSIGNED NOT NULL,
  `descripEnvio` VARCHAR(20) NULL,
  PRIMARY KEY (`idTipoEnvio`),
  UNIQUE INDEX `idTipoEnvio_UNIQUE` (`idTipoEnvio` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`tienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`tienda` (
  `idTienda` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(65) NULL,
  `codigoPostalId` SMALLINT UNSIGNED NULL,
  `localidadId` SMALLINT UNSIGNED NULL,
  `provinciaId` SMALLINT UNSIGNED NULL,
  PRIMARY KEY (`idTienda`),
  UNIQUE INDEX `idTienda_UNIQUE` (`idTienda` ASC) VISIBLE,
  INDEX `Provincia_idx` (`provinciaId` ASC) VISIBLE,
  INDEX `localidad_tienda_idx` (`localidadId` ASC) VISIBLE,
  INDEX `codigoPostal_tienda_idx` (`codigoPostalId` ASC) VISIBLE,
  CONSTRAINT `provincia_tienda`
    FOREIGN KEY (`provinciaId`)
    REFERENCES `Pizzeria`.`provincia` (`idProvincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `localidad_tienda`
    FOREIGN KEY (`localidadId`)
    REFERENCES `Pizzeria`.`localidad` (`idLocalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `codigoPostal_tienda`
    FOREIGN KEY (`codigoPostalId`)
    REFERENCES `Pizzeria`.`codigoPostal` (`idCodigoPostal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`pedidos` (
  `idPedidos` INT UNSIGNED NOT NULL,
  `tipoEnvioId` TINYINT UNSIGNED NULL,
  `clienteId` SMALLINT UNSIGNED NULL,
  `precioTotal` DECIMAL(6,2) NULL,
  `tiendaId` SMALLINT UNSIGNED NULL,
  `fechaPedido` DATETIME NULL DEFAULT curdate(),
  PRIMARY KEY (`idPedidos`),
  UNIQUE INDEX `idPedidos_UNIQUE` (`idPedidos` ASC) VISIBLE,
  INDEX `Cliente_idx` (`clienteId` ASC) VISIBLE,
  INDEX `TipoEnvio_idx` (`tipoEnvioId` ASC) VISIBLE,
  INDEX `Tienda_idx` (`tiendaId` ASC) VISIBLE,
  CONSTRAINT `Cliente`
    FOREIGN KEY (`clienteId`)
    REFERENCES `Pizzeria`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TipoEnvio`
    FOREIGN KEY (`tipoEnvioId`)
    REFERENCES `Pizzeria`.`tipoEnvio` (`idTipoEnvio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Tienda`
    FOREIGN KEY (`tiendaId`)
    REFERENCES `Pizzeria`.`tienda` (`idTienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`tipoProd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`tipoProd` (
  `idTipoProd` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipoProdDescrip` VARCHAR(15) NULL,
  PRIMARY KEY (`idTipoProd`),
  UNIQUE INDEX `idTipoProd_UNIQUE` (`idTipoProd` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`producto` (
  `idProducto` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descrip` VARCHAR(45) NULL,
  `imagen` VARCHAR(2048) NULL,
  `precio` DECIMAL(5,2) NULL,
  `tipoProdId` TINYINT UNSIGNED NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `Tipo Producto_idx` (`tipoProdId` ASC) VISIBLE,
  UNIQUE INDEX `idProducto_UNIQUE` (`idProducto` ASC) VISIBLE,
  CONSTRAINT `Tipo Producto`
    FOREIGN KEY (`tipoProdId`)
    REFERENCES `Pizzeria`.`tipoProd` (`idTipoProd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`pedidosProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`pedidosProducto` (
  `idPedidosProducto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pedidoId` INT UNSIGNED NULL,
  `productoId` SMALLINT UNSIGNED NULL DEFAULT 0,
  `cantidadProd` TINYINT UNSIGNED NULL DEFAULT 0,
  `precioTotal` DECIMAL(6,2) NULL,
  PRIMARY KEY (`idPedidosProducto`),
  UNIQUE INDEX `idPedidosProducto_UNIQUE` (`idPedidosProducto` ASC) VISIBLE,
  INDEX `Pedidos_idx` (`pedidoId` ASC) VISIBLE,
  INDEX `Productos_idx` (`productoId` ASC) VISIBLE,
  CONSTRAINT `Pedidos`
    FOREIGN KEY (`pedidoId`)
    REFERENCES `Pizzeria`.`pedidos` (`idPedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Productos`
    FOREIGN KEY (`productoId`)
    REFERENCES `Pizzeria`.`producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`categorias` (
  `idCategoria` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `categoDescrip` VARCHAR(30) NULL,
  PRIMARY KEY (`idCategoria`),
  UNIQUE INDEX `idCategoPizza_UNIQUE` (`idCategoria` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`categoPizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`categoPizza` (
  `idCategoPizza` INT NOT NULL,
  `categoId` TINYINT UNSIGNED NULL,
  `pizzaId` SMALLINT UNSIGNED NULL,
  PRIMARY KEY (`idCategoPizza`),
  INDEX `producto_idx` (`pizzaId` ASC) VISIBLE,
  INDEX `categoria_idx` (`categoId` ASC) VISIBLE,
  UNIQUE INDEX `pizzaId_UNIQUE` (`pizzaId` ASC) VISIBLE,
  CONSTRAINT `producto`
    FOREIGN KEY (`pizzaId`)
    REFERENCES `Pizzeria`.`producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `categoria`
    FOREIGN KEY (`categoId`)
    REFERENCES `Pizzeria`.`categorias` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`tipoEmpleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`tipoEmpleado` (
  `iTtipoEmpleado` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipoEmplDescip` VARCHAR(15) NULL,
  PRIMARY KEY (`iTtipoEmpleado`),
  UNIQUE INDEX `iTtipoEmpleado_UNIQUE` (`iTtipoEmpleado` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`empleados` (
  `idEmpleados` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `nif` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `tipoEmpleadoId` TINYINT UNSIGNED NULL,
  `tiendaId` SMALLINT UNSIGNED NULL,
  PRIMARY KEY (`idEmpleados`),
  UNIQUE INDEX `idEmpleados_UNIQUE` (`idEmpleados` ASC) VISIBLE,
  INDEX `tienda_idx` (`tiendaId` ASC) VISIBLE,
  INDEX `Tipo empleado_idx` (`tipoEmpleadoId` ASC) VISIBLE,
  CONSTRAINT `tienda`
    FOREIGN KEY (`tiendaId`)
    REFERENCES `Pizzeria`.`tienda` (`idTienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Tipo empleado`
    FOREIGN KEY (`tipoEmpleadoId`)
    REFERENCES `Pizzeria`.`tipoEmpleado` (`iTtipoEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`pedidosDomicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`pedidosDomicilio` (
  `idPedidosDomicilio` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pedidoId` INT UNSIGNED NULL,
  `empleadoId` SMALLINT UNSIGNED NULL,
  `fechaEntrega` DATETIME NULL,
  PRIMARY KEY (`idPedidosDomicilio`),
  UNIQUE INDEX `idPedidosDomicilio_UNIQUE` (`idPedidosDomicilio` ASC) VISIBLE,
  UNIQUE INDEX `pedidoId_UNIQUE` (`pedidoId` ASC) VISIBLE,
  INDEX `Empleado_idx` (`empleadoId` ASC) VISIBLE,
  CONSTRAINT `Pedido`
    FOREIGN KEY (`pedidoId`)
    REFERENCES `Pizzeria`.`pedidos` (`idPedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Empleado`
    FOREIGN KEY (`empleadoId`)
    REFERENCES `Pizzeria`.`empleados` (`idEmpleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
