-- MySQL Script generated by MySQL Workbench
-- Mon Feb  5 12:41:34 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Optica_Cul_Ampolla
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Optica_Cul_Ampolla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Optica_Cul_Ampolla` DEFAULT CHARACTER SET utf8 ;
USE `Optica_Cul_Ampolla` ;

-- -----------------------------------------------------
-- Table `Optica_Cul_Ampolla`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica_Cul_Ampolla`.`ciudad` (
  `idCiudad` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomCiudad` VARCHAR(25) NULL,
  PRIMARY KEY (`idCiudad`),
  UNIQUE INDEX `idCiudad_UNIQUE` (`idCiudad` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica_Cul_Ampolla`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica_Cul_Ampolla`.`pais` (
  `idPais` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomPais` VARCHAR(20) NULL,
  UNIQUE INDEX `idpais_UNIQUE` (`idPais` ASC) VISIBLE,
  PRIMARY KEY (`idPais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica_Cul_Ampolla`.`proveidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica_Cul_Ampolla`.`proveidor` (
  `idProveidor` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nif` VARCHAR(9) NOT NULL,
  `nombre` VARCHAR(20) NULL,
  `telefono` VARCHAR(15) NULL,
  `fax` VARCHAR(15) NULL,
  `calle` VARCHAR(30) NULL,
  `numPortal` TINYINT NULL,
  `piso` TINYINT NULL,
  `puerta` VARCHAR(4) NULL,
  `codigoPostal` VARCHAR(5) NULL,
  `ciudadId` SMALLINT UNSIGNED NULL,
  `paisId` SMALLINT UNSIGNED NULL,
  UNIQUE INDEX `NIF_UNIQUE` (`nif` ASC) VISIBLE,
  INDEX `idCiudad_idx` (`ciudadId` ASC) VISIBLE,
  INDEX `idPais_idx` (`paisId` ASC) VISIBLE,
  PRIMARY KEY (`idProveidor`),
  UNIQUE INDEX `idProveedor_UNIQUE` (`idProveidor` ASC) VISIBLE,
  CONSTRAINT `idCiudad`
    FOREIGN KEY (`ciudadId`)
    REFERENCES `Optica_Cul_Ampolla`.`ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPais`
    FOREIGN KEY (`paisId`)
    REFERENCES `Optica_Cul_Ampolla`.`pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica_Cul_Ampolla`.`tipoMontura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica_Cul_Ampolla`.`tipoMontura` (
  `idTipoMontura` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripMontura` VARCHAR(10) NULL,
  PRIMARY KEY (`idTipoMontura`),
  UNIQUE INDEX `idtipoMontura_UNIQUE` (`idTipoMontura` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica_Cul_Ampolla`.`color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica_Cul_Ampolla`.`color` (
  `idColor` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripColor` VARCHAR(20) NULL,
  UNIQUE INDEX `idcolorVidrio_UNIQUE` (`idColor` ASC) VISIBLE,
  PRIMARY KEY (`idColor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica_Cul_Ampolla`.`gafas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica_Cul_Ampolla`.`gafas` (
  `idGafas` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(30) NULL,
  `graduacion_izq` DECIMAL(4,2) UNSIGNED NULL,
  `graduacion_der` DECIMAL(4,2) UNSIGNED NULL,
  `precio` DECIMAL(6,2) UNSIGNED NULL,
  `monturaId` SMALLINT UNSIGNED NULL,
  `colorMonturaId` SMALLINT UNSIGNED NULL,
  `colorVidrioId` SMALLINT UNSIGNED NULL,
  `proveidorId` SMALLINT UNSIGNED NULL,
  PRIMARY KEY (`idGafas`),
  UNIQUE INDEX `idGafas_UNIQUE` (`idGafas` ASC) VISIBLE,
  INDEX `idProveedor_idx` (`proveidorId` ASC) VISIBLE,
  INDEX `idtipoMontura_idx` (`monturaId` ASC) VISIBLE,
  INDEX `colorMontura_idx` (`colorMonturaId` ASC) VISIBLE,
  INDEX `colorVidrio_idx` (`colorVidrioId` ASC) VISIBLE,
  CONSTRAINT `idProveedor`
    FOREIGN KEY (`proveidorId`)
    REFERENCES `Optica_Cul_Ampolla`.`proveidor` (`idProveidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idtipoMontura`
    FOREIGN KEY (`monturaId`)
    REFERENCES `Optica_Cul_Ampolla`.`tipoMontura` (`idTipoMontura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `colorMontura`
    FOREIGN KEY (`colorMonturaId`)
    REFERENCES `Optica_Cul_Ampolla`.`color` (`idColor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `colorVidrio`
    FOREIGN KEY (`colorVidrioId`)
    REFERENCES `Optica_Cul_Ampolla`.`color` (`idColor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica_Cul_Ampolla`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica_Cul_Ampolla`.`clientes` (
  `idClientes` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NULL,
  `calle` VARCHAR(30) NULL,
  `numPortal` TINYINT UNSIGNED NULL,
  `piso` TINYINT UNSIGNED NULL,
  `puerta` VARCHAR(4) NULL,
  `codigoPostal` VARCHAR(5) NULL,
  `telefono` VARCHAR(15) NULL,
  `email` VARCHAR(45) NULL,
  `fechaRegistro` DATE NULL,
  `ciudadId` SMALLINT UNSIGNED NULL,
  `recomendadoId` SMALLINT UNSIGNED NULL DEFAULT 0,
  PRIMARY KEY (`idClientes`),
  UNIQUE INDEX `idClientes_UNIQUE` (`idClientes` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `idCiudad_idx` (`ciudadId` ASC) VISIBLE,
  INDEX `ClienteRecomendado_idx` (`recomendadoId` ASC) VISIBLE,
  CONSTRAINT `idCiudad`
    FOREIGN KEY (`ciudadId`)
    REFERENCES `Optica_Cul_Ampolla`.`ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ClienteRecomendado`
    FOREIGN KEY (`recomendadoId`)
    REFERENCES `Optica_Cul_Ampolla`.`clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica_Cul_Ampolla`.`vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica_Cul_Ampolla`.`vendedor` (
  `idVendedor` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NULL,
  PRIMARY KEY (`idVendedor`),
  UNIQUE INDEX `idVendedor_UNIQUE` (`idVendedor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica_Cul_Ampolla`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica_Cul_Ampolla`.`ventas` (
  `idVentas` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `vendedorId` SMALLINT UNSIGNED NULL,
  `clienteId` SMALLINT UNSIGNED NULL,
  `gafaId` SMALLINT UNSIGNED NULL,
  `fechaVenta` DATE NULL DEFAULT curdate(),
  PRIMARY KEY (`idVentas`),
  UNIQUE INDEX `idVentas_UNIQUE` (`idVentas` ASC) VISIBLE,
  INDEX `idVendedor_idx` (`vendedorId` ASC) VISIBLE,
  INDEX `idCliente_idx` (`clienteId` ASC) VISIBLE,
  INDEX `idGafas_idx` (`gafaId` ASC) VISIBLE,
  CONSTRAINT `idVendedor`
    FOREIGN KEY (`vendedorId`)
    REFERENCES `Optica_Cul_Ampolla`.`vendedor` (`idVendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCliente`
    FOREIGN KEY (`clienteId`)
    REFERENCES `Optica_Cul_Ampolla`.`clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idGafas`
    FOREIGN KEY (`gafaId`)
    REFERENCES `Optica_Cul_Ampolla`.`gafas` (`idGafas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
