select nombre from producto;
select nombre, precio from producto;
select * from producto;
select nombre, concat(precio,"€"), concat(precio,"$") from producto;
select nombre as "Nombre del producto", concat(precio,"€") as Euros, concat(precio,"$") as Dolares from producto;
select upper(nombre), precio from producto;
select lower(nombre), precio from producto;
select nombre, upper(substring(nombre,1,2)) from fabricante;
select nombre, round(precio,0) as "Precio redondeado" from producto;
select nombre, truncate(precio,0) as "Precio truncate" from producto;
select fabricante.codigo from fabricante inner join producto on fabricante.codigo = producto.codigo_fabricante;
select fabricante.codigo from fabricante inner join producto on fabricante.codigo = producto.codigo_fabricante group by fabricante.codigo;
select nombre from fabricante order by nombre asc;
select nombre from fabricante order by nombre desc;
select nombre,precio from producto order by nombre asc, precio desc;
select * from producto limit 5;
select * from producto limit 3,2;
select nombre, precio from producto order by precio asc limit 1;
select nombre, precio from producto order by precio desc limit 1;
select nombre from producto where codigo_fabricante = 2;
select producto.nombre, producto.precio, fabricante.nombre from producto inner join fabricante on producto.codigo_fabricante = fabricante.codigo;
select producto.nombre, producto.precio, fabricante.nombre from producto inner join fabricante on producto.codigo_fabricante = fabricante.codigo order by fabricante.nombre asc;
select producto.codigo, producto.nombre, fabricante.codigo, fabricante.nombre from producto inner join fabricante on producto.codigo_fabricante = fabricante.codigo;
select producto.nombre, producto.precio, fabricante.nombre from producto inner join fabricante on producto.codigo_fabricante = fabricante.codigo order by precio asc limit 1;
select producto.nombre, producto.precio, fabricante.nombre from producto inner join fabricante on producto.codigo_fabricante = fabricante.codigo order by precio desc limit 1;
select producto.* from producto inner join fabricante on producto.codigo_fabricante = fabricante.codigo where fabricante.nombre = "Lenovo";
select producto.* from producto inner join fabricante on producto.codigo_fabricante = fabricante.codigo where fabricante.nombre = "Crucial" and producto.precio > 200;
select producto.* from producto inner join fabricante on producto.codigo_fabricante = fabricante.codigo where fabricante.nombre = "Asus" or fabricante.nombre = "Hewlett-Packard" or fabricante.nombre = "Seagate";
select producto.* from producto inner join fabricante on producto.codigo_fabricante = fabricante.codigo where fabricante.nombre in ("Asus","Hewlett-Packard","Seagate");
select producto.nombre, producto.precio from producto inner join fabricante on producto.codigo_fabricante = fabricante.codigo where fabricante.nombre like "%e";
select producto.nombre, producto.precio from producto inner join fabricante on producto.codigo_fabricante = fabricante.codigo where fabricante.nombre like "%w%";
select producto.nombre, producto.precio, fabricante.nombre from producto inner join fabricante on producto.codigo_fabricante = fabricante.codigo where producto.precio >= 180 order by producto.precio desc, producto.nombre asc;
select fabricante.codigo, fabricante.nombre from fabricante inner join producto on fabricante.codigo = producto.codigo_fabricante group by fabricante.codigo;
select fabricante.nombre, producto.nombre from fabricante left join producto on fabricante.codigo = producto.codigo_fabricante;
select fabricante.nombre from fabricante left join producto on fabricante.codigo = producto.codigo_fabricante where isnull(producto.nombre);
select producto.* from producto where producto.codigo_fabricante in (select fabricante.codigo from fabricante where fabricante.nombre = "Lenovo");
select producto.* from producto where producto.precio in (select max(producto.precio) from producto where producto.codigo_fabricante in (select fabricante.codigo from fabricante where fabricante.nombre = "Lenovo"));
select producto.nombre from producto inner join fabricante on producto.codigo_fabricante = fabricante.codigo where fabricante.nombre = "Lenovo" order by producto.precio desc limit 1;
select producto.nombre from producto inner join fabricante on producto.codigo_fabricante = fabricante.codigo where fabricante.nombre = "Hewlett-Packard" order by producto.precio asc limit 1;
select producto.* from producto where producto.precio >= any (select max(producto.precio) from producto inner join fabricante on producto.codigo_fabricante = fabricante.codigo where fabricante.nombre = "Lenovo");
select producto.* from producto inner join fabricante on producto.codigo_fabricante = fabricante.codigo where fabricante.nombre = "Asus" and producto.precio > any (select avg(producto.precio) from producto inner join fabricante on producto.codigo_fabricante = fabricante.codigo where fabricante.nombre = "Asus");